export const CATEGORY_ICON_ASSETS: Record<string, string> = {
  餐饮: '/assets/category-icons-png/餐饮.png',
  购物: '/assets/category-icons-png/购物.png',
  交通: '/assets/category-icons-png/交通.png',
  水电: '/assets/category-icons-png/水电.png',
  服装: '/assets/category-icons-png/服装.png',
  医疗: '/assets/category-icons-png/医疗.png',
  美妆: '/assets/category-icons-png/美妆.png',
  美容: '/assets/category-icons-png/美妆.png',
  娱乐: '/assets/category-icons-png/娱乐.png',
  通讯: '/assets/category-icons-png/通讯.png',
  汽车: '/assets/category-icons-png/汽车.png',
  烟酒: '/assets/category-icons-png/烟酒.png',
  书籍: '/assets/category-icons-png/书籍.png',
  宠物: '/assets/category-icons-png/宠物.png',
  孩子: '/assets/category-icons-png/孩子.png',
  居家: '/assets/category-icons-png/居家.png',
  旅行: '/assets/category-icons-png/旅行.png',
  送礼: '/assets/category-icons-png/送礼.png',
  家电: '/assets/category-icons-png/家电.png',
  零食: '/assets/category-icons-png/零食.png',
  数码: '/assets/category-icons-png/数码.png',
  住房: '/assets/category-icons-png/住房.png',
  日用: '/assets/category-icons-png/日用.png',
  维修: '/assets/category-icons-png/维修.png',
  运动: '/assets/category-icons-png/运动.png',
  充值: '/assets/category-icons-png/充值.png',
  工资: '/assets/category-icons-png/工资.png',
  水果: '/assets/category-icons-png/水果.png',
  社交: '/assets/category-icons-png/社交.png',
  转账: '/assets/category-icons-png/转账.png',
  红包: '/assets/category-icons-png/红包.png',
  办公: '/assets/category-icons-png/办公.png',
  快递: '/assets/category-icons-png/快递.png',
  买菜: '/assets/category-icons-png/买菜.png',
  花呗: '/assets/category-icons-png/花呗.png',
  设置: '/assets/category-icons-png/设置.png',
}

export function getCategoryIconAsset(name: string, fallback = '') {
  return CATEGORY_ICON_ASSETS[name] || fallback
}
